/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author thega
 */
import java.sql.*;
import javax.swing.JOptionPane;

public class AjoutVehicule_App extends javax.swing.JFrame {

    Statement st;
    DBConnect DBC = new DBConnect();

    /**
     * Creates new form AjoutVehicule_App
     */
    public AjoutVehicule_App() {
        initComponents();
        couleurComboBox();
        carburantComboBox();
        boiteVitComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "deprecation"})
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        marqueLabel = new javax.swing.JLabel();
        dateAchatLabel = new javax.swing.JLabel();
        prixAchatLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        marqueText = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        anneeSortieText = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        prixAchatText = new javax.swing.JTextPane();
        fermer = new javax.swing.JButton();
        register = new javax.swing.JButton();
        modeleLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        modeleText = new javax.swing.JTextPane();
        nbreKilomLabel = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        kilomText = new javax.swing.JTextPane();
        nbrePorteLabel = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        porteText = new javax.swing.JTextPane();
        typeCarburLabel = new javax.swing.JLabel();
        couleurLabel = new javax.swing.JLabel();
        puissFiscLabel = new javax.swing.JLabel();
        boitVitessLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        gestionVehicule = new javax.swing.JLabel();
        titreAjoutLabel = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        puissFiscText = new javax.swing.JTextPane();
        couleur_jComboBox = new javax.swing.JComboBox<>();
        carburant_jComboBox = new javax.swing.JComboBox<>();
        boiteVit_jComboBox = new javax.swing.JComboBox<>();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        marqueLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        marqueLabel.setForeground(new java.awt.Color(0, 56, 168));
        marqueLabel.setText("Marque: ");

        dateAchatLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        dateAchatLabel.setForeground(new java.awt.Color(0, 56, 168));
        dateAchatLabel.setText("Année d'achat: ");

        prixAchatLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        prixAchatLabel.setForeground(new java.awt.Color(0, 56, 168));
        prixAchatLabel.setText("Prix d'achat: ");

        marqueText.setContentType(""); // NOI18N
        marqueText.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        marqueText.setToolTipText("\"Nissan\", \"Renault\", \"Audi\"...");
        marqueText.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        marqueText.setName("AjoutMarque"); // NOI18N
        jScrollPane2.setViewportView(marqueText);
        marqueText.getAccessibleContext().setAccessibleName("AjoutMarque");

        anneeSortieText.setContentType(""); // NOI18N
        anneeSortieText.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        anneeSortieText.setToolTipText("\"2012\", \"1998\", 2006\"...");
        anneeSortieText.setName("AjoutMarque"); // NOI18N
        jScrollPane3.setViewportView(anneeSortieText);

        prixAchatText.setContentType(""); // NOI18N
        prixAchatText.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        prixAchatText.setToolTipText("\"25000\", \"18000\", \"27000\"...");
        prixAchatText.setName("AjoutMarque"); // NOI18N
        jScrollPane4.setViewportView(prixAchatText);

        fermer.setBackground(new java.awt.Color(204, 204, 204));
        fermer.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        fermer.setForeground(new java.awt.Color(0, 56, 168));
        fermer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        fermer.setLabel("Fermer");
        fermer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fermerMouseClicked(evt);
            }
        });
        fermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fermerActionPerformed(evt);
            }
        });

        register.setBackground(new java.awt.Color(204, 204, 204));
        register.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        register.setForeground(new java.awt.Color(0, 56, 168));
        register.setText("Enregistrer");
        register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register.setMaximumSize(new java.awt.Dimension(89, 40));
        register.setMinimumSize(new java.awt.Dimension(89, 40));
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        modeleLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        modeleLabel.setForeground(new java.awt.Color(0, 56, 168));
        modeleLabel.setText("Modèle:");

        modeleText.setContentType(""); // NOI18N
        modeleText.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        modeleText.setToolTipText("\"Mégane\", \"208\", Clio\"...");
        modeleText.setName("AjoutMarque"); // NOI18N
        jScrollPane5.setViewportView(modeleText);

        nbreKilomLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        nbreKilomLabel.setForeground(new java.awt.Color(0, 56, 168));
        nbreKilomLabel.setText("Kilométrages:");

        kilomText.setContentType(""); // NOI18N
        kilomText.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        kilomText.setToolTipText("\"250000\", \"125000\", \"160000\"...");
        kilomText.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        kilomText.setName("AjoutMarque"); // NOI18N
        jScrollPane6.setViewportView(kilomText);

        nbrePorteLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        nbrePorteLabel.setForeground(new java.awt.Color(0, 56, 168));
        nbrePorteLabel.setText("Nombre portes:");

        porteText.setContentType(""); // NOI18N
        porteText.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        porteText.setToolTipText("\"3\", \"5\"...");
        porteText.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        porteText.setName("AjoutMarque"); // NOI18N
        jScrollPane7.setViewportView(porteText);

        typeCarburLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        typeCarburLabel.setForeground(new java.awt.Color(0, 56, 168));
        typeCarburLabel.setText("Type carburant:");

        couleurLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        couleurLabel.setForeground(new java.awt.Color(0, 56, 168));
        couleurLabel.setText("Couleur:");

        puissFiscLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        puissFiscLabel.setForeground(new java.awt.Color(0, 56, 168));
        puissFiscLabel.setText("Puissance fiscale:");

        boitVitessLabel.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        boitVitessLabel.setForeground(new java.awt.Color(0, 56, 168));
        boitVitessLabel.setText("Boite de vitesses:");

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(490, 200));

        gestionVehicule.setBackground(new java.awt.Color(255, 255, 255));
        gestionVehicule.setFont(new java.awt.Font("Dialog", 3, 48)); // NOI18N
        gestionVehicule.setForeground(new java.awt.Color(255, 255, 255));
        gestionVehicule.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Desktop\\Travails\\NetBeansProjects\\Vehicule\\assets\\GestiVec.png")); // NOI18N

        titreAjoutLabel.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        titreAjoutLabel.setForeground(new java.awt.Color(255, 255, 255));
        titreAjoutLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titreAjoutLabel.setText("Ajouter un Vehicule");
        titreAjoutLabel.setAlignmentY(0.0F);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(titreAjoutLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gestionVehicule)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(gestionVehicule))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titreAjoutLabel)
                .addGap(48, 48, 48))
        );

        puissFiscText.setContentType(""); // NOI18N
        puissFiscText.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        puissFiscText.setToolTipText("\"125\", \"110\", \"90\"...");
        puissFiscText.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        puissFiscText.setName("AjoutMarque"); // NOI18N
        jScrollPane10.setViewportView(puissFiscText);

        couleur_jComboBox.setBackground(new java.awt.Color(255, 255, 255));
        couleur_jComboBox.setPreferredSize(new java.awt.Dimension(10, 33));
        couleur_jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                couleur_jComboBoxActionPerformed(evt);
            }
        });

        carburant_jComboBox.setBackground(new java.awt.Color(255, 255, 255));
        carburant_jComboBox.setPreferredSize(new java.awt.Dimension(10, 33));
        carburant_jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carburant_jComboBoxActionPerformed(evt);
            }
        });

        boiteVit_jComboBox.setBackground(new java.awt.Color(255, 255, 255));
        boiteVit_jComboBox.setPreferredSize(new java.awt.Dimension(10, 33));
        boiteVit_jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boiteVit_jComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(modeleLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nbreKilomLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(nbrePorteLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(242, 242, 242))
                                .addComponent(marqueLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(prixAchatLabel, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dateAchatLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(151, 151, 151)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(couleurLabel)
                            .addComponent(typeCarburLabel)
                            .addComponent(puissFiscLabel)
                            .addComponent(boitVitessLabel))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(carburant_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(couleur_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(boiteVit_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fermer)
                        .addGap(23, 23, 23))))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1109, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(marqueLabel))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(couleur_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(couleurLabel))
                            .addGap(1, 1, 1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(modeleLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(typeCarburLabel)
                            .addComponent(carburant_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateAchatLabel)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(prixAchatLabel)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(puissFiscLabel)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(boiteVit_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boitVitessLabel))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(nbreKilomLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nbrePorteLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(fermer)))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fermerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fermerMouseClicked
        dispose();
    }//GEN-LAST:event_fermerMouseClicked

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        String marque = marqueText.getText();
        String modele = modeleText.getText();
        String anneeSortie = anneeSortieText.getText();
        String prixAchat = prixAchatText.getText();
        String kilom = kilomText.getText();
        String porte = porteText.getText();
        String puissFisc = puissFiscText.getText();

        String rqt = "BEGIN; "
                + "INSERT INTO couleur(nomCouleur) "
                + "VALUES('" + couleur_jComboBox.getSelectedItem() + "'); "
                
                + "INSERT INTO moteur(carburant, puissanceFiscale, boiteVitesse) "
                + "VALUES('" + carburant_jComboBox.getSelectedItem() + "', '" + puissFisc + "', '" + boiteVit_jComboBox.getSelectedItem() + "'); "
                
                + "INSERT INTO vehicule(marque, modele, anneeSortie, prixAchat, kilometrage, nbrePortes, idCouleur, idMoteur) "
                + "VALUES('" + marque + "', '" + modele + "' ,'" + anneeSortie + "', '" + prixAchat + "', '" + kilom + "', '" + porte + "', LAST_INSERT_ID(), LAST_INSERT_ID()); "
                
                + "COMMIT;";

        try {
            st = DBC.ObtenirConnexion().createStatement();
            st.executeUpdate(rqt);
            JOptionPane.showMessageDialog(null, "Votre véhicule a bien été ajouté !");

            marqueText.setText("");
            modeleText.setText("");
            anneeSortieText.setText("");
            prixAchatText.setText("");
            kilomText.setText("");

        } catch (Exception ex) {
            System.out.println("Error: " + ex);
        }
    }//GEN-LAST:event_registerActionPerformed

    private void fermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fermerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fermerActionPerformed

    private void couleur_jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_couleur_jComboBoxActionPerformed

    }//GEN-LAST:event_couleur_jComboBoxActionPerformed

    private void carburant_jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carburant_jComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carburant_jComboBoxActionPerformed

    private void boiteVit_jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boiteVit_jComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boiteVit_jComboBoxActionPerformed

    private void couleurComboBox() {
        String rqt = "SELECT nomCouleur FROM couleur;";

        try {
            st = DBC.ObtenirConnexion().createStatement();
            ResultSet resultat = st.executeQuery(rqt);
            while (resultat.next()) {
                String couleur = resultat.getString("nomCouleur");
                couleur_jComboBox.addItem(couleur);
            }

        } catch (Exception ex) {
            System.out.println("Error: " + ex);
        }
    }

    private void carburantComboBox() {
        String rqt = "SELECT DISTINCT carburant FROM moteur;";

        try {
            st = DBC.ObtenirConnexion().createStatement();
            ResultSet resultat = st.executeQuery(rqt);
            while (resultat.next()) {
                String carburant = resultat.getString("carburant");
                carburant_jComboBox.addItem(carburant);
            }

        } catch (Exception ex) {
            System.out.println("Error: " + ex);
        }
    }

    private void boiteVitComboBox() {
        String rqt = "SELECT DISTINCT boiteVitesse FROM moteur;";

        try {
            st = DBC.ObtenirConnexion().createStatement();
            ResultSet resultat = st.executeQuery(rqt);
            while (resultat.next()) {
                String boiteVitesse = resultat.getString("boiteVitesse");
                boiteVit_jComboBox.addItem(boiteVitesse);
            }

        } catch (Exception ex) {
            System.out.println("Error: " + ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutVehicule_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutVehicule_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutVehicule_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutVehicule_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjoutVehicule_App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane anneeSortieText;
    private javax.swing.JLabel boitVitessLabel;
    private javax.swing.JComboBox<String> boiteVit_jComboBox;
    private javax.swing.JComboBox<String> carburant_jComboBox;
    private javax.swing.JLabel couleurLabel;
    private javax.swing.JComboBox<String> couleur_jComboBox;
    private javax.swing.JLabel dateAchatLabel;
    private javax.swing.JButton fermer;
    private javax.swing.JLabel gestionVehicule;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane kilomText;
    private javax.swing.JLabel marqueLabel;
    private javax.swing.JTextPane marqueText;
    private javax.swing.JLabel modeleLabel;
    private javax.swing.JTextPane modeleText;
    private javax.swing.JLabel nbreKilomLabel;
    private javax.swing.JLabel nbrePorteLabel;
    private javax.swing.JTextPane porteText;
    private javax.swing.JLabel prixAchatLabel;
    private javax.swing.JTextPane prixAchatText;
    private javax.swing.JLabel puissFiscLabel;
    private javax.swing.JTextPane puissFiscText;
    private javax.swing.JButton register;
    private javax.swing.JLabel titreAjoutLabel;
    private javax.swing.JLabel typeCarburLabel;
    // End of variables declaration//GEN-END:variables
}
