/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author thega
 */
public class Vehicule_App extends javax.swing.JFrame {

    /**
     * Creates new form Vehicule_App
     */
    public Vehicule_App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        gestionVehicule = new javax.swing.JLabel();
        ailtech = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ajoutBoutton = new javax.swing.JButton();
        voirBoutton = new javax.swing.JButton();
        quitter = new javax.swing.JButton();
        infoVersion = new javax.swing.JLabel();
        infoAuteur = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(960, 458));
        setMinimumSize(new java.awt.Dimension(960, 458));
        setPreferredSize(new java.awt.Dimension(1203, 650));
        setResizable(false);
        setSize(new java.awt.Dimension(1203, 650));

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        gestionVehicule.setBackground(new java.awt.Color(255, 255, 255));
        gestionVehicule.setFont(new java.awt.Font("Dialog", 3, 48)); // NOI18N
        gestionVehicule.setForeground(new java.awt.Color(255, 255, 255));
        gestionVehicule.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Desktop\\Travails\\NetBeansProjects\\Vehicule\\assets\\GestiVec.png")); // NOI18N

        ailtech.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Desktop\\Travails\\NetBeansProjects\\Vehicule\\assets\\ailTECH.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(ailtech)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 719, Short.MAX_VALUE)
                .addComponent(gestionVehicule)
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ailtech)
                    .addComponent(gestionVehicule))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        ajoutBoutton.setBackground(new java.awt.Color(204, 204, 204));
        ajoutBoutton.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        ajoutBoutton.setForeground(new java.awt.Color(0, 56, 168));
        ajoutBoutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Desktop\\Travails\\NetBeansProjects\\Vehicule\\assets\\cross_logo3.png")); // NOI18N
        ajoutBoutton.setText("Ajouter Vehicule");
        ajoutBoutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ajoutBoutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ajoutBouttonMouseClicked(evt);
            }
        });
        ajoutBoutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutBouttonActionPerformed(evt);
            }
        });

        voirBoutton.setBackground(new java.awt.Color(204, 204, 204));
        voirBoutton.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        voirBoutton.setForeground(new java.awt.Color(0, 56, 168));
        voirBoutton.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Desktop\\Travails\\NetBeansProjects\\Vehicule\\assets\\car_logo3.png")); // NOI18N
        voirBoutton.setText("Voir Vehicules ajoutés");
        voirBoutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        voirBoutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voirBouttonMouseClicked(evt);
            }
        });
        voirBoutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voirBouttonActionPerformed(evt);
            }
        });

        quitter.setBackground(new java.awt.Color(204, 204, 204));
        quitter.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        quitter.setForeground(new java.awt.Color(0, 56, 168));
        quitter.setText("Quitter");
        quitter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitterMouseClicked(evt);
            }
        });

        infoVersion.setForeground(new java.awt.Color(51, 102, 255));
        infoVersion.setText("Version: 1.0");

        infoAuteur.setForeground(new java.awt.Color(51, 102, 255));
        infoAuteur.setText("App by Ryan.L");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoAuteur)
                    .addComponent(infoVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(quitter)
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(ajoutBoutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 281, Short.MAX_VALUE)
                .addComponent(voirBoutton)
                .addGap(50, 50, 50))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voirBoutton)
                    .addComponent(ajoutBoutton))
                .addGap(150, 150, 150)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(quitter)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(infoVersion)
                        .addGap(0, 0, 0)
                        .addComponent(infoAuteur)))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajoutBouttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutBouttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ajoutBouttonActionPerformed

    private void voirBouttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voirBouttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_voirBouttonActionPerformed

    private void quitterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitterMouseClicked
        System.exit(0);
    }//GEN-LAST:event_quitterMouseClicked

    private void ajoutBouttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ajoutBouttonMouseClicked
        AjoutVehicule_App AppelFenetreAjout = new AjoutVehicule_App();
        AppelFenetreAjout.setVisible(true);
    }//GEN-LAST:event_ajoutBouttonMouseClicked

    private void voirBouttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voirBouttonMouseClicked
        VoirVehicule_App AppelFenetreVoir = new VoirVehicule_App();
        AppelFenetreVoir.setVisible(true);
    }//GEN-LAST:event_voirBouttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vehicule_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vehicule_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vehicule_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vehicule_App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vehicule_App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ailtech;
    private javax.swing.JButton ajoutBoutton;
    private javax.swing.JLabel gestionVehicule;
    private javax.swing.JLabel infoAuteur;
    private javax.swing.JLabel infoVersion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton quitter;
    private javax.swing.JButton voirBoutton;
    // End of variables declaration//GEN-END:variables
}
